# Generated by Django 4.2.16 on 2025-05-15 17:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
