# Generated by Django 4.2.16 on 2025-05-18 18:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_alter_information_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
