# Generated by Django 4.2.16 on 2025-06-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('flag', models.ImageField(blank=True, null=True, upload_to='flags/')),
            ],
        ),
    ]
