# Generated by Django 4.2.16 on 2025-03-14 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='country_id',
        ),
    ]
