# Generated by Django 4.2.16 on 2025-06-20 12:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_lots_id', models.BigIntegerField(unique=True)),
                ('make', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('series', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=255, null=True)),
                ('body_class', models.CharField(blank=True, max_length=255, null=True)),
                ('make_id', models.IntegerField(blank=True, null=True)),
                ('model_id', models.IntegerField(blank=True, null=True)),
                ('series_id', models.IntegerField(blank=True, null=True)),
                ('vehicle_type_id', models.IntegerField(blank=True, null=True)),
                ('body_class_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuperuserLastSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filters', models.JSONField(default=dict)),
                ('job_cancelled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.BigIntegerField(blank=True, null=True)),
                ('vin', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('auction_name', models.CharField(blank=True, max_length=255, null=True)),
                ('make', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('body_style', models.CharField(blank=True, max_length=255, null=True)),
                ('car_keys', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('cylinders', models.CharField(blank=True, max_length=20, null=True)),
                ('doc_type', models.CharField(blank=True, max_length=255, null=True)),
                ('drive', models.CharField(blank=True, max_length=255, null=True)),
                ('engine_type', models.CharField(blank=True, max_length=255, null=True)),
                ('est_retail_value', models.FloatField(blank=True, null=True)),
                ('fuel', models.CharField(blank=True, max_length=255, null=True)),
                ('highlights', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('lot_number', models.BigIntegerField(blank=True, null=True)),
                ('odometer', models.FloatField(blank=True, null=True)),
                ('primary_damage', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_damage', models.CharField(blank=True, max_length=255, null=True)),
                ('seller', models.CharField(blank=True, max_length=255, null=True)),
                ('series', models.CharField(blank=True, max_length=255, null=True)),
                ('transmission', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=255, null=True)),
                ('is_insurance', models.BooleanField(blank=True, null=True)),
                ('currency_name', models.CharField(blank=True, max_length=50, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('car_photo_urls', models.TextField(blank=True, default=list, null=True, verbose_name=models.URLField())),
                ('damage_photos', models.TextField(blank=True, default=list, null=True, verbose_name=models.URLField())),
                ('buy_now_price_histories', models.JSONField(blank=True, default=dict, null=True)),
                ('sales_history', models.JSONField(blank=True, default=dict, null=True)),
                ('active_bidding', models.JSONField(blank=True, default=dict, null=True)),
                ('buy_now_car', models.JSONField(blank=True, default=dict, null=True)),
                ('to_be_updated', models.BooleanField(default=True)),
                ('to_be_published', models.BooleanField(default=True)),
                ('car_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.carinfo')),
            ],
        ),
    ]
