# Generated by Django 4.2.16 on 2025-04-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_orders_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
