{
    "series": [
        [
            {
                "emp_driver_id": 88041,
                "tlc_desc": "TIRE ISSUE REQUIRES TOW TO SHOP",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-07",
                "call_id": 6522904,
                "driver": "DEREK MCANDREW,",
                "service_resolution": "OTHER TIRE-RELATED PROBLEM (DESCRIBE)",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "SATISFIED",
                "response_time": "TOTALLY SATISFIED",
                "kept_informed": "TOTALLY SATISFIED",
                "member_comments": "THANKS",
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 48.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-08",
                "NE_Driver_id": "78107",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 61531,
                "tlc_desc": "MEMBER REQUESTS BATTERY SERVICE",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-07",
                "call_id": 6524932,
                "driver": "TIMOTHY ADAMS,",
                "service_resolution": "BOOST - BATTERY TEST PASSED",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "SATISFIED",
                "kept_informed": "SATISFIED",
                "member_comments": null,
                "requesting_service": "SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 42.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-15",
                "NE_Driver_id": "76964",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 20525,
                "tlc_desc": "KEY LOCKED IN PASSENGER COMPARTMENT",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-07",
                "call_id": 6525767,
                "driver": "DYMETRIS NUNEZ",
                "service_resolution": "UNLOCK VEHICLE W/O KEY",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "TOTALLY SATISFIED",
                "kept_informed": "TOTALLY SATISFIED",
                "member_comments": "SERVICE WAS FAST AND QUICK TO TAKE CARE OF THE SITUATION ",
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 16.0,
                "trouble_code": "TOW",
                "Recorded_date": "2025-02-09",
                "NE_Driver_id": "75602",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 84399,
                "tlc_desc": "OTHER REQUIRED TOW (DESCRIBE)",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-07",
                "call_id": 6525915,
                "driver": "SCOTT LYONS,",
                "service_resolution": "BOOST ONLY - BATTERY TEST NOT DONE",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "SATISFIED",
                "kept_informed": "TOTALLY SATISFIED",
                "member_comments": "SCOTT WAS GREAT!  I THOUGHT I NEEDED A TOW TO GARAGE, BUT HE FOUND THE CAUSE OF MY NOISE UNDER THE HOOD- A LONG WRENCH  HAD BEEN LEFT BY A MECHANIC WHO REPLACED A BELT LAST WEEK. ",
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 55.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-08",
                "NE_Driver_id": "77806",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 21164,
                "tlc_desc": "FLAT TIRE W/SPARE",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-07",
                "call_id": 6526166,
                "driver": "JIM COST",
                "service_resolution": "INSTALL SPARE TIRE",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "TOTALLY SATISFIED",
                "kept_informed": "TOTALLY SATISFIED",
                "member_comments": "CALLED ABOUT FLAT TIRE AND HAD THE SPARE PUT ON WITHIN AN HOUR- TECHNICIAN WAS PROMPT, FRIENDLY AND PROFESSIONAL.",
                "requesting_service": "SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 67.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-08",
                "NE_Driver_id": "72254",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 1,
                "tlc_desc": "MEMBER REQUESTS TOW",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-07",
                "call_id": 6526405,
                "driver": "UNKNOWN DRIVER",
                "service_resolution": "CANCEL CALL - SERVICE NOT EN ROUTE",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "UNKNOWN",
                "response_time": "UNKNOWN",
                "kept_informed": "UNKNOWN",
                "member_comments": "HE WAS VERY HELPFUL AND PERSONAL. I WOULD USE HIS COMPANY AGAIN.",
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": null,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-13",
                "NE_Driver_id": null,
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 21164,
                "tlc_desc": "NO CRANK - JUMP START",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-07",
                "call_id": 6526662,
                "driver": "JIM COST",
                "service_resolution": "BOOST ONLY - BATTERY TEST NOT DONE",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "UNKNOWN",
                "response_time": "UNKNOWN",
                "kept_informed": "UNKNOWN",
                "member_comments": null,
                "requesting_service": "UNKNOWN",
                "Actual_Time_of_Arrival_(minutes)": 38.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-18",
                "NE_Driver_id": "72254",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 84520,
                "tlc_desc": "TIRE ISSUE REQUIRES TOW TO SHOP",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-07",
                "call_id": 6527198,
                "driver": "DANIEL GESELL,",
                "service_resolution": "DAMAGED - NO REPAIR & NO SPARE",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "SATISFIED",
                "kept_informed": "TOTALLY SATISFIED",
                "member_comments": null,
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 58.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-09",
                "NE_Driver_id": "77820",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 85168,
                "tlc_desc": "NO CRANK - JUMP START",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-08",
                "call_id": 6529482,
                "driver": "CURTIS MANNING,",
                "service_resolution": "BOOST ONLY - BATTERY TEST NOT DONE",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "TOTALLY SATISFIED",
                "kept_informed": "TOTALLY SATISFIED",
                "member_comments": "PERFECT",
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 39.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-09",
                "NE_Driver_id": "77880",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 85168,
                "tlc_desc": "NO CRANK - JUMP START",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-08",
                "call_id": 6529511,
                "driver": "CURTIS MANNING,",
                "service_resolution": "BOOST - BATTERY TEST PASSED",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "TOTALLY SATISFIED",
                "kept_informed": "TOTALLY SATISFIED",
                "member_comments": "VERY HELPFUL MECHANIC, PROFESSIONAL AND PROMPT. HE GAVE VERY GOOD ADVICE WHICH WAS EXTREMELY HELPFUL AND IMPORTANT TO FIX MY CAR. GREAT ADVICE AND KNOWLEDGEABLE. GREAT EXPERIENCE ",
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 63.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-09",
                "NE_Driver_id": "77880",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 81740,
                "tlc_desc": "OUT OF GASOLINE",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-08",
                "call_id": 6530852,
                "driver": "JONATHAN CLINE,",
                "service_resolution": "FUEL DELIVERY - GASOLINE",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "TOTALLY SATISFIED",
                "kept_informed": "TOTALLY SATISFIED",
                "member_comments": "CAR RAN OUT OF GAS. CALLED AAA AND HAD A DRIVER AT MY LOCATION IN UNDER 20 MINS. DRIVER WAS EXTREMELY POLITE, QUICK AND EFFICIENT! LIFE SAVER!",
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 28.0,
                "trouble_code": "BATTERY",
                "Recorded_date": "2025-02-12",
                "NE_Driver_id": "77505",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 82120,
                "tlc_desc": "NO CRANK - JUMP START",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-08",
                "call_id": 6531695,
                "driver": "JOHN C,",
                "service_resolution": "BOOST ONLY - BATTERY TEST NOT DONE",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "TOTALLY SATISFIED",
                "kept_informed": "TOTALLY SATISFIED",
                "member_comments": "I DRIVER WAS SUPER NICE AND KNOWLEDGEABLE. I WAS VERY PLEASED!",
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 17.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-09",
                "NE_Driver_id": "77577",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 85168,
                "tlc_desc": "MEMBER REQUESTS BATTERY SERVICE",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-08",
                "call_id": 6533301,
                "driver": "CURTIS MANNING,",
                "service_resolution": "BOOST - CHARGE AND RETEST RESULT",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "NEITHER SATISFIED NOR DISATISFIED",
                "kept_informed": "NEITHER SATISFIED NOR DISATISFIED",
                "member_comments": "TOOK ALMOST AN HOUR BEFORE THEY DISPATCHED SOMEONE TO HELP ME. ",
                "requesting_service": "NEITHER SATISFIED NOR DISATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 37.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-09",
                "NE_Driver_id": "77880",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 83520,
                "tlc_desc": "OTHER REQUIRED TOW (DESCRIBE)",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-08",
                "call_id": 6533450,
                "driver": "RYAN FRATUS,",
                "service_resolution": "MEMBER REQUESTS TOW",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "TOTALLY SATISFIED",
                "kept_informed": "TOTALLY SATISFIED",
                "member_comments": "ALL PERSONNEL WERE VERY CARING AND POLITE ",
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 23.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-09",
                "NE_Driver_id": "77709",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 82120,
                "tlc_desc": "EXTRICATION - PROBABLE TOW",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-08",
                "call_id": 6533574,
                "driver": "JOHN C,",
                "service_resolution": "EXTRICATION ONLY",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "TOTALLY SATISFIED",
                "kept_informed": "TOTALLY SATISFIED",
                "member_comments": "JOHN, THE DRIVER WHO HELPED US OUT, WAS ESPECIALLY GOOD AT HIS JOB!  HE WAS QUICK TO ARRIVE AND HELPED US OUT OF A DIFFICULT SITUATION. JOHN WAS ALSO VERY PERSONABLE AND GAVE US SOME GOOD ADVICE.  GREAT GUY!  ",
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 42.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-09",
                "NE_Driver_id": "77577",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 20757,
                "tlc_desc": "AXLE/DRIVESHAFT/SUSPENSION FAILURE",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-08",
                "call_id": 6533757,
                "driver": "DAVID GRAHAM",
                "service_resolution": "MEMBER REQUESTS TOW",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "SATISFIED",
                "kept_informed": "TOTALLY SATISFIED",
                "member_comments": "BESIDES THE LONG WAIT FOR THE TOW, EVERYTHING ELSE WENT WELL.  CUSTOMER SERVICE WAS OUTSTANDING ON BOTH AAA AND TOW UPDATES AND DRIVER ",
                "requesting_service": "SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 142.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-09",
                "NE_Driver_id": "76092",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 84520,
                "tlc_desc": "OTHER REQUIRED TOW (DESCRIBE)",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-08",
                "call_id": 6534560,
                "driver": "DANIEL GESELL,",
                "service_resolution": "CONVENIENCE/MEMBER CONCERN TOW",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "TOTALLY SATISFIED",
                "kept_informed": "TOTALLY SATISFIED",
                "member_comments": null,
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 125.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-16",
                "NE_Driver_id": "77820",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 104208,
                "tlc_desc": "KEY LOCKED IN PASSENGER COMPARTMENT",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-08",
                "call_id": 6537159,
                "driver": "ZACHARY VINCENT",
                "service_resolution": "UNLOCK VEHICLE W/O KEY",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "TOTALLY SATISFIED",
                "kept_informed": "TOTALLY SATISFIED",
                "member_comments": "EXCELLENT SERVICE ",
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 33.0,
                "trouble_code": "TOW",
                "Recorded_date": "2025-02-09",
                "NE_Driver_id": "78356",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 85168,
                "tlc_desc": "KEY LOCKED IN PASSENGER COMPARTMENT",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-09",
                "call_id": 6539132,
                "driver": "CURTIS MANNING,",
                "service_resolution": "UNLOCK VEHICLE W/O KEY",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "TOTALLY SATISFIED",
                "kept_informed": "TOTALLY SATISFIED",
                "member_comments": "I WAS LOCKED OUT OF MY CAR WELL IT WAS STILL RUNNING AND THE AAA PROVIDER WAS VERY EFFICIENT AND GOT INTO MY CAR WITHIN 3",
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 34.0,
                "trouble_code": "TOW",
                "Recorded_date": "2025-02-10",
                "NE_Driver_id": "77880",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 21153,
                "tlc_desc": "NO CRANK - JUMP START",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-09",
                "call_id": 6540429,
                "driver": "JAKE BAKER",
                "service_resolution": "BOOST - BATTERY TEST PASSED",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "TOTALLY SATISFIED",
                "kept_informed": "TOTALLY SATISFIED",
                "member_comments": "JUST GREAT!!!",
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 45.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-13",
                "NE_Driver_id": "76524",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 81740,
                "tlc_desc": "EXTRICATION - PROBABLE GO",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-09",
                "call_id": 6540989,
                "driver": "JONATHAN CLINE,",
                "service_resolution": "EXTRICATION ONLY",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "TOTALLY SATISFIED",
                "kept_informed": "TOTALLY SATISFIED",
                "member_comments": "JOHNATHAN C WITH FIVE STAR TOWING INC. WAS GREAT! HE WAS QUICK, FRIENDLY, AND VERY KNOWLEDGEABLE!",
                "requesting_service": "DISSATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 29.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-10",
                "NE_Driver_id": "77505",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 21153,
                "tlc_desc": "MEMBER REQUESTS BATTERY SERVICE",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "0",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-09",
                "call_id": 6541049,
                "driver": "JAKE BAKER",
                "service_resolution": "BOOST - BATTERY TEST PASSED",
                "overall_satisfaction": "SATISFIED",
                "driver_sat": "SATISFIED",
                "response_time": "TOTALLY SATISFIED",
                "kept_informed": "TOTALLY SATISFIED",
                "member_comments": null,
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 39.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-10",
                "NE_Driver_id": "76524",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 104208,
                "tlc_desc": "MEMBER REQUESTS TOW",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-09",
                "call_id": 6541701,
                "driver": "ZACHARY VINCENT",
                "service_resolution": "UNABLE TO PRIME FUEL SYSTEM",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "TOTALLY SATISFIED",
                "kept_informed": "TOTALLY SATISFIED",
                "member_comments": "VERY FAST RESPONSE TIME WHICH WAS VERY IMPORTANT THIS PARTICULAR DAY. ",
                "requesting_service": "SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 27.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-10",
                "NE_Driver_id": "78356",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 81740,
                "tlc_desc": "EXTRICATION - PROBABLE GO",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-09",
                "call_id": 6541892,
                "driver": "JONATHAN CLINE,",
                "service_resolution": "EXTRICATION ONLY",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "TOTALLY SATISFIED",
                "kept_informed": "TOTALLY SATISFIED",
                "member_comments": "IT WAS GREAT WITHIN 40 MINUTES MY TOW TRUCK DRIVER ARRIVE. ",
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 36.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-10",
                "NE_Driver_id": "77505",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 1,
                "tlc_desc": "OTHER REQUIRED TOW (DESCRIBE)",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-09",
                "call_id": 6542497,
                "driver": "UNKNOWN DRIVER",
                "service_resolution": "CANCEL CALL - SERVICE NOT EN ROUTE",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "UNKNOWN",
                "response_time": "UNKNOWN",
                "kept_informed": "UNKNOWN",
                "member_comments": "EXCELLENT SERVICE ",
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": null,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-11",
                "NE_Driver_id": null,
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 82120,
                "tlc_desc": "EXTRICATION - PROBABLE GO",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-09",
                "call_id": 6542812,
                "driver": "JOHN C,",
                "service_resolution": "EXTRICATION ONLY",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "TOTALLY SATISFIED",
                "kept_informed": "TOTALLY SATISFIED",
                "member_comments": null,
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 23.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-10",
                "NE_Driver_id": "77577",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 1,
                "tlc_desc": "KEY LOCKED IN PASSENGER COMPARTMENT",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-10",
                "call_id": 6543470,
                "driver": "UNKNOWN DRIVER",
                "service_resolution": "CANCEL CALL - SERVICE NOT EN ROUTE",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "UNKNOWN",
                "response_time": "UNKNOWN",
                "kept_informed": "UNKNOWN",
                "member_comments": null,
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": null,
                "trouble_code": "TOW",
                "Recorded_date": "2025-02-14",
                "NE_Driver_id": null,
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 104208,
                "tlc_desc": "MEMBER REQUESTS TOW",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-10",
                "call_id": 6543670,
                "driver": "ZACHARY VINCENT",
                "service_resolution": "MEMBER REQUESTS TOW",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "NEITHER SATISFIED NOR DISATISFIED",
                "kept_informed": "NEITHER SATISFIED NOR DISATISFIED",
                "member_comments": null,
                "requesting_service": "SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 77.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-11",
                "NE_Driver_id": "78356",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": "N/A",
                "tlc_desc": "MEMBER REQUESTS TOW",
                "lost_call": 1,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "FIRSTOWNSIT",
                "facility_id": "4418",
                "facility_name": "LOPEZ AUTOMOTIVE INC. (MA)",
                "service_date": "2025-02-10",
                "call_id": 6544095,
                "driver": "N/A",
                "service_resolution": "CONVENIENCE/MEMBER CONCERN TOW",
                "overall_satisfaction": "DISSATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "TOTALLY DISSATISFIED",
                "kept_informed": "SATISFIED",
                "member_comments": "N/A",
                "requesting_service": "NEITHER SATISFIED NOR DISATISFIED",
                "Actual_Time_of_Arrival_(minutes)": null,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-11",
                "NE_Driver_id": "78413",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)",
                "org_svc_facl_id__name": "N/A"
            },
            {
                "emp_driver_id": 21153,
                "tlc_desc": "MEMBER REQUESTS BATTERY SERVICE",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-10",
                "call_id": 6544136,
                "driver": "JAKE BAKER",
                "service_resolution": "BOOST - BATTERY TEST PASSED",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "TOTALLY SATISFIED",
                "kept_informed": "TOTALLY SATISFIED",
                "member_comments": null,
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 26.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-11",
                "NE_Driver_id": "76524",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 21153,
                "tlc_desc": "NO CRANK - JUMP START",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-10",
                "call_id": 6544486,
                "driver": "JAKE BAKER",
                "service_resolution": "REPLACE BAT (NEW) - TEST FAIL",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "TOTALLY SATISFIED",
                "kept_informed": "TOTALLY SATISFIED",
                "member_comments": "HE WAS VERY HELPFUL IN DETERMINING CHANGING OUT THE BATTERY. HE WAS VERY PROFESSIONAL AND COURTEOUS.",
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 55.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-11",
                "NE_Driver_id": "76524",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 21164,
                "tlc_desc": "OTHER REQUIRED TOW (DESCRIBE)",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-10",
                "call_id": 6545351,
                "driver": "JIM COST",
                "service_resolution": "CONVENIENCE/MEMBER CONCERN TOW",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "TOTALLY SATISFIED",
                "kept_informed": "TOTALLY SATISFIED",
                "member_comments": "TOW TRUCK DRIVER WAS GREAT \nAAA KEPT ME INFORMED ",
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 85.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-14",
                "NE_Driver_id": "72254",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 20525,
                "tlc_desc": "BRAKE SYSTEM FAILURE",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-10",
                "call_id": 6545380,
                "driver": "DYMETRIS NUNEZ",
                "service_resolution": null,
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "TOTALLY SATISFIED",
                "kept_informed": "TOTALLY SATISFIED",
                "member_comments": "THE TOW TRUCK DRIVER WAS EXCELLENT VERY FAST",
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 130.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-12",
                "NE_Driver_id": "75602",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 61531,
                "tlc_desc": "KEY LOCKED IN TRUNK W/TRUNK RELEASE",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "0",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-10",
                "call_id": 6545391,
                "driver": "TIMOTHY ADAMS,",
                "service_resolution": "UNLOCK VEHICLE W/O KEY",
                "overall_satisfaction": "TOTALLY DISSATISFIED",
                "driver_sat": "TOTALLY DISSATISFIED",
                "response_time": "TOTALLY DISSATISFIED",
                "kept_informed": "TOTALLY DISSATISFIED",
                "member_comments": "WAITING  FOR A CALL 978939 9077",
                "requesting_service": "TOTALLY DISSATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 39.0,
                "trouble_code": "TOW",
                "Recorded_date": "2025-02-11",
                "NE_Driver_id": "76964",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 88041,
                "tlc_desc": "OTHER REQUIRED TOW (DESCRIBE)",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-10",
                "call_id": 6545458,
                "driver": "DEREK MCANDREW,",
                "service_resolution": "OTHER SERVICE (DESCRIBE)",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "TOTALLY SATISFIED",
                "kept_informed": "TOTALLY SATISFIED",
                "member_comments": "IT WAS A VERY PLEASANT EXPERIENCE. I EXPECTED IT TO BE THREE OR FOUR HOURS. WAIT I WAS SHOCKED WHEN HE WAS SHOCKED WHEN HE WAS THERE IN A HALF HOUR GREAT SERVICE",
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 60.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-11",
                "NE_Driver_id": "78107",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 61531,
                "tlc_desc": "FLAT TIRE W/SPARE",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-10",
                "call_id": 6545535,
                "driver": "TIMOTHY ADAMS,",
                "service_resolution": "INSTALL SPARE TIRE",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "TOTALLY SATISFIED",
                "kept_informed": "TOTALLY SATISFIED",
                "member_comments": null,
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 121.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-14",
                "NE_Driver_id": "76964",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 25350,
                "tlc_desc": "OTHER REQUIRED TOW (DESCRIBE)",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-10",
                "call_id": 6546290,
                "driver": "HARLEY DELANCEY",
                "service_resolution": "CONVENIENCE/MEMBER CONCERN TOW",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "TOTALLY SATISFIED",
                "kept_informed": "TOTALLY SATISFIED",
                "member_comments": "THE DRIVER ARRIVED PROMPTLY AND WENT ABOVE AND BEYOND TO MAKE ME COMFORTABLE WITH THE HEAT BLASTING AND WAS VERY KIND. ",
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 59.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-14",
                "NE_Driver_id": "76540",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 84520,
                "tlc_desc": "MEMBER REQUESTS TOW",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "0",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-10",
                "call_id": 6546434,
                "driver": "DANIEL GESELL,",
                "service_resolution": "ACCIDENT ASSIST - SECOND TOW",
                "overall_satisfaction": "SATISFIED",
                "driver_sat": "UNKNOWN",
                "response_time": "SATISFIED",
                "kept_informed": "SATISFIED",
                "member_comments": "MY CAR CRASHED IN LEOMINSTER AND I NEEDED TO GET  IT TO FRAMINGHAM. I COULDNT BE WITH THE CAR WHICH WAS AT A TOW COMPANY. THINGS WORKED OUT GREAT..",
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": "604",
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-14",
                "NE_Driver_id": "77820",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 21153,
                "tlc_desc": "FLAT TIRE W/SPARE",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-10",
                "call_id": 6546674,
                "driver": "JAKE BAKER",
                "service_resolution": "INSTALL SPARE TIRE",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "TOTALLY SATISFIED",
                "kept_informed": "TOTALLY SATISFIED",
                "member_comments": null,
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 53.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-11",
                "NE_Driver_id": "76524",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 81740,
                "tlc_desc": "MEMBER REQUESTS TOW",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "0",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-10",
                "call_id": 6546971,
                "driver": "JONATHAN CLINE,",
                "service_resolution": "MEMBER REQUESTS TOW",
                "overall_satisfaction": "SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "SATISFIED",
                "kept_informed": "NEITHER SATISFIED NOR DISATISFIED",
                "member_comments": "GREAT WITH THE HELP OF TRIPLE A DRIVER BUT WAS MADE TO PAY MY RECEIPT OF A BILL FROM A TOWING COMPANY THE STATE POLICE CALLED FOR ME ON THEIR OWN. AND NOT REIMBURSED BY TRIPLE A",
                "requesting_service": "NEITHER SATISFIED NOR DISATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 464.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-14",
                "NE_Driver_id": "77505",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 25350,
                "tlc_desc": "OTHER REQUIRED TOW (DESCRIBE)",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-10",
                "call_id": 6547406,
                "driver": "HARLEY DELANCEY",
                "service_resolution": "COLLISION/POLICE TOW",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "TOTALLY SATISFIED",
                "kept_informed": "TOTALLY SATISFIED",
                "member_comments": "EXCELLENT ",
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 95.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-11",
                "NE_Driver_id": "76540",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 21153,
                "tlc_desc": "FLAT TIRE W/SPARE",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-10",
                "call_id": 6547794,
                "driver": "JAKE BAKER",
                "service_resolution": "INSTALL SPARE TIRE",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "TOTALLY SATISFIED",
                "kept_informed": "TOTALLY SATISFIED",
                "member_comments": null,
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 24.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-11",
                "NE_Driver_id": "76524",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 104208,
                "tlc_desc": "OTHER REQUIRED TOW (DESCRIBE)",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-10",
                "call_id": 6548309,
                "driver": "ZACHARY VINCENT",
                "service_resolution": "CONVENIENCE/MEMBER CONCERN TOW",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "SATISFIED",
                "kept_informed": "TOTALLY SATISFIED",
                "member_comments": null,
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 72.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-11",
                "NE_Driver_id": "78356",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 81740,
                "tlc_desc": "MEMBER REQUESTS TOW",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "0",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-10",
                "call_id": 6548413,
                "driver": "JONATHAN CLINE,",
                "service_resolution": "CANCEL CALL - SERVICE NOT EN ROUTE",
                "overall_satisfaction": "TOTALLY DISSATISFIED",
                "driver_sat": "UNKNOWN",
                "response_time": "UNKNOWN",
                "kept_informed": "UNKNOWN",
                "member_comments": null,
                "requesting_service": "TOTALLY DISSATISFIED",
                "Actual_Time_of_Arrival_(minutes)": null,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-11",
                "NE_Driver_id": "77505",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 21153,
                "tlc_desc": "MEMBER REQUESTS BATTERY SERVICE",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-10",
                "call_id": 6548424,
                "driver": "JAKE BAKER",
                "service_resolution": "REPLACE BAT (NEW) - TEST FAIL",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "TOTALLY SATISFIED",
                "kept_informed": "TOTALLY SATISFIED",
                "member_comments": "TECH WAS GREAT,",
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 19.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-14",
                "NE_Driver_id": "76524",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 21164,
                "tlc_desc": "TIRE ISSUE REQUIRES TOW TO SHOP",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-10",
                "call_id": 6548885,
                "driver": "JIM COST",
                "service_resolution": "DAMAGED - NO REPAIR & NO SPARE",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "TOTALLY SATISFIED",
                "kept_informed": "TOTALLY SATISFIED",
                "member_comments": null,
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 148.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-11",
                "NE_Driver_id": "72254",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 104208,
                "tlc_desc": "EXTRICATION - PROBABLE GO",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-10",
                "call_id": 6549355,
                "driver": "ZACHARY VINCENT",
                "service_resolution": "CANCEL CALL - SERVICE NOT EN ROUTE",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "UNKNOWN",
                "response_time": "UNKNOWN",
                "kept_informed": "UNKNOWN",
                "member_comments": null,
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": null,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-11",
                "NE_Driver_id": "78356",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 25350,
                "tlc_desc": "MEMBER REQUESTS TOW",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-10",
                "call_id": 6549827,
                "driver": "HARLEY DELANCEY",
                "service_resolution": "MEMBER REQUESTS TOW",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "SATISFIED",
                "kept_informed": "SATISFIED",
                "member_comments": null,
                "requesting_service": "SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 129.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-11",
                "NE_Driver_id": "76540",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 84399,
                "tlc_desc": "OTHER REQUIRED TOW (DESCRIBE)",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-10",
                "call_id": 6550568,
                "driver": "SCOTT LYONS,",
                "service_resolution": "CONVENIENCE/MEMBER CONCERN TOW",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "TOTALLY SATISFIED",
                "kept_informed": "TOTALLY SATISFIED",
                "member_comments": "SCOTT TOW TRUCK DRIVER KIND HELPFUL THE BEST!",
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 109.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-13",
                "NE_Driver_id": "77806",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            },
            {
                "emp_driver_id": 21164,
                "tlc_desc": "KNOWN STARTER PROBLEM",
                "lost_call": 0,
                "real_first_shop_decline_minutes": 0.0,
                "survey_bucket_new": "1",
                "facility_id": "4424",
                "facility_name": "FIVE STAR TOWING INC (MA)",
                "service_date": "2025-02-10",
                "call_id": 6550712,
                "driver": "JIM COST",
                "service_resolution": "MEMBER REQUESTS TOW",
                "overall_satisfaction": "TOTALLY SATISFIED",
                "driver_sat": "TOTALLY SATISFIED",
                "response_time": "TOTALLY SATISFIED",
                "kept_informed": "TOTALLY SATISFIED",
                "member_comments": null,
                "requesting_service": "TOTALLY SATISFIED",
                "Actual_Time_of_Arrival_(minutes)": 78.0,
                "trouble_code": "LIGHT SERVICE",
                "Recorded_date": "2025-02-11",
                "NE_Driver_id": "72254",
                "org_survey_assigned__name": "4424",
                "org_business_survey_assigned__name": "FIVE STAR TOWING INC (MA)"
            }
        ]
    ],
    "labels": [],
    "y_axis_options": [],
    "column_config": {},
    "original_length": 1364,
    "meta": {
        "dates": {
            "start": "2025-02-01",
            "end": "2025-04-30",
            "upload_start": "2021-01-01",
            "upload_end": "2025-05-16"
        },
        "pages": 3
    },
    "incentive_periods": [
        {
            "start": "2025-02-01",
            "end": "2025-04-30"
        },
        {
            "id": 159,
            "name": "March Performance Period (January - March)",
            "start": "2025-01-01",
            "end": "2025-03-31",
            "type": "csn",
            "recorded_cutoff": "2025-04-16",
            "recorded_cutoff_time": "2025-04-16T23:59:59Z",
            "show_until": "2025-04-22"
        }
    ]
}