# Generated by Django 4.2.16 on 2025-06-17 22:37

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipping', '0001_initial'),
        ('car_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionActiveBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction', models.IntegerField()),
                ('all_lots_id', models.BigIntegerField()),
                ('sale_date', models.BigIntegerField()),
                ('current_bid', models.FloatField()),
                ('date_updated', models.BigIntegerField()),
                ('bid_updated', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AuctionCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('char_code', models.CharField(max_length=10)),
                ('iso_code', models.IntegerField()),
                ('code_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AuctionVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cylinders', models.IntegerField(blank=True, null=True)),
                ('odometer', models.IntegerField()),
                ('zero_to_hundred', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('motor_power', models.IntegerField(blank=True, null=True)),
                ('motor_power_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('battery_range', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('engine_power_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('engine_power', models.IntegerField(blank=True, null=True)),
                ('engine_type', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', tinymce.models.HTMLField(blank=True, null=True)),
                ('VIN', models.TextField(blank=True, null=True)),
                ('currency', models.TextField()),
                ('price_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.FloatField()),
                ('number_of_seats', models.IntegerField()),
                ('is_published', models.BooleanField(default=True)),
                ('documents', models.TextField(blank=True, null=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('supplier_id', models.BigIntegerField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('to_be_updated', models.BooleanField(default=True)),
                ('body_style', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car_details.bodystyle')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car_details.color')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shipping.country')),
                ('drive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car_details.drive')),
                ('feature_list', models.ManyToManyField(related_name='feature_list_auction_vehicles', to='car_details.feature')),
                ('fuel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car_details.fuel')),
                ('label_list', models.ManyToManyField(related_name='label_list_auction_vehicles', to='car_details.label')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_details.make')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_details.model')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car_details.status')),
                ('transmission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car_details.transmission')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_name', models.CharField(max_length=255)),
                ('lot_number', models.BigIntegerField()),
                ('car_keys', models.CharField(blank=True, max_length=20, null=True)),
                ('primary_damage', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_damage', models.CharField(blank=True, max_length=100, null=True)),
                ('highlights', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(max_length=255)),
                ('est_retail_value', models.FloatField(blank=True, null=True)),
                ('is_insurance', models.BooleanField(null=True)),
                ('doc_type', models.CharField(blank=True, max_length=100, null=True)),
                ('vin', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('damage_photos', models.JSONField(blank=True, null=True)),
                ('car_info', models.JSONField(blank=True, null=True)),
                ('sales_history_last', models.JSONField(blank=True, null=True)),
                ('sales_history', models.JSONField(blank=True, null=True)),
                ('buy_now_car', models.JSONField(blank=True, null=True)),
                ('active_bidding', models.ManyToManyField(blank=True, to='auction.auctionactivebid')),
                ('auctionvehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_vehicles', to='auction.auctionvehicle')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auction.auctioncurrency')),
            ],
        ),
    ]
