# Generated by Django 4.2.16 on 2025-06-18 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_name', models.CharField(max_length=255)),
                ('auction_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.BigIntegerField()),
                ('car_keys', models.CharField(blank=True, max_length=20, null=True)),
                ('primary_damage', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_damage', models.CharField(blank=True, max_length=100, null=True)),
                ('highlights', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(max_length=255)),
                ('est_retail_value', models.FloatField(blank=True, null=True)),
                ('is_insurance', models.BooleanField(null=True)),
                ('doc_type', models.CharField(blank=True, max_length=100, null=True)),
                ('vin', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('damage_photos', models.JSONField(blank=True, null=True)),
                ('car_info', models.JSONField(blank=True, null=True)),
                ('sales_history_last', models.JSONField(blank=True, null=True)),
                ('sales_history', models.JSONField(blank=True, null=True)),
                ('buy_now_car', models.JSONField(blank=True, null=True)),
                ('active_bidding', models.ManyToManyField(blank=True, to='auction.auctionactivebid')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_details', to='auction.auction')),
                ('auctionvehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_vehicles', to='auction.auctionvehicle')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auction.auctioncurrency')),
            ],
        ),
        migrations.DeleteModel(
            name='AuctionDetails',
        ),
    ]
