# Generated by Django 4.2.16 on 2025-06-18 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auction_auctiondetail_delete_auctiondetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyNowPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('auctionvehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_now_price_history', to='auction.auctionvehicle')),
            ],
        ),
    ]
