# Generated by Django 4.2.16 on 2025-06-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_buynowpricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctiondetail',
            name='buyer_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='auctiondetail',
            name='purchase_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auctiondetail',
            name='sale_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auctiondetail',
            name='sale_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
