# Generated by Django 4.2.16 on 2025-06-18 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auctiondetail_buyer_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionVehicleMedia',
            fields=[
                ('vehicle_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('api_id', models.IntegerField(blank=True, null=True)),
                ('all_lots_id', models.BigIntegerField(blank=True, null=True)),
                ('vin', models.TextField(blank=True, null=True)),
                ('img_url_from_api', models.TextField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('video_path', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.auctionvehicle')),
            ],
        ),
    ]
