# Generated by Django 4.2.16 on 2025-06-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_details', '0001_initial'),
        ('auction', '0005_auctionvehiclemedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionvehicle',
            name='currency',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='auctionvehicle',
            name='feature_list',
            field=models.ManyToManyField(null=True, related_name='feature_list_auction_vehicles', to='car_details.feature'),
        ),
        migrations.AlterField(
            model_name='auctionvehicle',
            name='label_list',
            field=models.ManyToManyField(null=True, related_name='label_list_auction_vehicles', to='car_details.label'),
        ),
        migrations.AlterField(
            model_name='auctionvehicle',
            name='number_of_seats',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='auctionvehicle',
            name='odometer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='auctionvehicle',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
