# Generated by Django 4.2.16 on 2025-06-17 22:37

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_az', models.TextField()),
                ('name_en', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_az', models.TextField()),
                ('name_en', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_az', models.TextField()),
                ('name_en', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_az', models.TextField()),
                ('name_en', models.TextField()),
                ('color_hex', models.CharField(blank=True, max_length=7, null=True)),
                ('font_awesome_icon', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_az', models.TextField()),
                ('name_en', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_az', models.TextField()),
                ('name_en', models.TextField()),
                ('color_hex', models.CharField(blank=True, max_length=7, null=True)),
                ('font_awesome_icon', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_details.make')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_az', models.TextField()),
                ('name_en', models.TextField()),
                ('color_hex', models.CharField(blank=True, max_length=7, null=True)),
                ('font_awesome_icon', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_az', models.TextField()),
                ('name_en', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cylinders', models.IntegerField(blank=True, null=True)),
                ('odometer', models.IntegerField()),
                ('zero_to_hundred', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('motor_power', models.IntegerField(blank=True, null=True)),
                ('motor_power_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('battery_range', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('engine_power_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('engine_power', models.IntegerField(blank=True, null=True)),
                ('engine_type', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', tinymce.models.HTMLField(blank=True, null=True)),
                ('VIN', models.TextField()),
                ('currency', models.TextField()),
                ('price_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.FloatField()),
                ('number_of_seats', models.IntegerField()),
                ('is_published', models.BooleanField()),
                ('documents', models.TextField(blank=True, null=True)),
                ('is_popular', models.BooleanField()),
                ('supplier_id', models.BigIntegerField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('body_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_details.bodystyle')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_details.color')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.country')),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_details.drive')),
                ('feature_list', models.ManyToManyField(related_name='vehicles', to='car_details.feature')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_details.fuel')),
                ('label_list', models.ManyToManyField(related_name='vehicles', to='car_details.label')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_details.make')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_details.model')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_details.status')),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_details.transmission')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMedia',
            fields=[
                ('vehicle_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('api_id', models.IntegerField(blank=True, null=True)),
                ('all_lots_id', models.BigIntegerField(blank=True, null=True)),
                ('vin', models.TextField(blank=True, null=True)),
                ('img_url_from_api', models.TextField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('video_path', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_details.vehicle')),
            ],
        ),
    ]
