# Generated by Django 4.2.16 on 2025-03-14 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMedia',
            fields=[
                ('vehicle_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('api_id', models.IntegerField()),
                ('all_lots_id', models.BigIntegerField()),
                ('vin', models.TextField()),
                ('img_url_from_api', models.TextField()),
                ('image_path', models.CharField(max_length=255)),
                ('video_path', models.CharField(max_length=255)),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_details.vehicle')),
            ],
        ),
    ]
