# Generated by Django 4.2.16 on 2025-03-14 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_details', '0002_vehiclemedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='make_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_details.make'),
        ),
    ]
