# Generated by Django 4.2.16 on 2025-03-14 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_remove_country_country_id'),
        ('car_details', '0003_alter_model_make_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.country'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
