# Generated by Django 4.2.16 on 2025-03-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_details', '0004_alter_vehicle_country_id_delete_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='documents',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='feature_list',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='label_list',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price_discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='supplier_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
