# Generated by Django 4.2.16 on 2025-03-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_details', '0005_alter_vehicle_comment_alter_vehicle_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(),
        ),
    ]
