# Generated by Django 4.2.16 on 2025-03-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_details', '0006_alter_vehicle_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemedia',
            name='all_lots_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemedia',
            name='api_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemedia',
            name='image_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemedia',
            name='img_url_from_api',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemedia',
            name='video_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemedia',
            name='vin',
            field=models.TextField(null=True),
        ),
    ]
