# Generated by Django 4.2.16 on 2025-03-24 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_details', '0007_alter_vehiclemedia_all_lots_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='make_id',
        ),
    ]
