# Generated by Django 4.2.16 on 2025-03-25 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_details', '0008_remove_vehicle_make_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='make_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='car_details.make'),
            preserve_default=False,
        ),
    ]
