# Generated by Django 4.2.16 on 2025-03-25 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_details', '0009_vehicle_make_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='make_id',
            new_name='make',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='make_id',
            new_name='make',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='model_id',
            new_name='model',
        ),
    ]
