# Generated by Django 4.2.16 on 2025-03-25 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_details', '0010_rename_make_id_model_make_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclemedia',
            old_name='vehicle_id',
            new_name='vehicle',
        ),
    ]
