# Generated by Django 4.2.16 on 2025-03-25 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_details', '0011_rename_vehicle_id_vehiclemedia_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='country_id',
            new_name='country',
        ),
    ]
