# Generated by Django 4.2.16 on 2025-05-07 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_details', '0014_alter_vehicle_comment_alter_vehicle_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='battery_range',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='motor_power',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='motor_power_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='zero_to_hundred',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
