# Generated by Django 4.2.16 on 2025-05-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_details', '0015_vehicle_battery_range_vehicle_motor_power_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='engine_power',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_power_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
