# Generated by Django 4.2.16 on 2025-05-07 08:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_details', '0016_alter_vehicle_engine_power_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='comment',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
