# Generated by Django 4.2.16 on 2025-05-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_details', '0017_alter_vehicle_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='label_color_hex',
        ),
        migrations.AddField(
            model_name='feature',
            name='color_hex',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='font_awesome_icon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='color_hex',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='font_awesome_icon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='feature_list',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='feature_list',
            field=models.ManyToManyField(related_name='vehicles', to='car_details.feature'),
        ),
    ]
