# Generated by Django 4.2.16 on 2025-05-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_details', '0018_remove_label_label_color_hex_feature_color_hex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemedia',
            name='all_lots_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemedia',
            name='api_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemedia',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemedia',
            name='img_url_from_api',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemedia',
            name='video_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemedia',
            name='vin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
