# Generated by Django 4.2.16 on 2025-05-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_details', '0019_alter_vehiclemedia_all_lots_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='label_list',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='label_list',
            field=models.ManyToManyField(related_name='vehicles', to='car_details.label'),
        ),
    ]
