# Generated by Django 4.2.16 on 2025-05-08 04:51

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('car_details', '0020_remove_vehicle_label_list_vehicle_label_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='comment',
            field=djrichtextfield.models.RichTextField(blank=True, null=True),
        ),
    ]
