# Generated by Django 4.2.16 on 2025-05-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_details', '0021_alter_vehicle_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='color_hex',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='font_awesome_icon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
