# Generated by Django 4.2.16 on 2025-05-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_details', '0023_alter_vehicle_engine_power_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='cylinders',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
