# Generated by Django 4.2.16 on 2025-05-20 18:12

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('car_details', '0025_alter_vehicle_engine_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='comment',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
